version: '3'

services:
  ibraim:
    container_name: ibraim
    image: nginx:latest
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.ibraim.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.ibraim.entrypoints=web
      - traefik.http.routers.ibraim-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.ibraim-https.entrypoints=websecure
      - traefik.http.routers.ibraim-https.tls=true
      - traefik.http.routers.ibraim-https.tls.certresolver=cloudflare
    restart: unless-stopped

networks:
  proxy:
    external: true
