version: '3'

services:
  ${CONTAINER_NAME}:
    container_name: ${CONTAINER_NAME}
    image: nginx:latest
    volumes:
      - ../public:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${CONTAINER_NAME}.entrypoints=web
      - traefik.http.routers.${CONTAINER_NAME}-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${CONTAINER_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${CONTAINER_NAME}-https.tls=true
      - traefik.http.routers.${CONTAINER_NAME}-https.tls.certresolver=cloudflare
    restart: unless-stopped

networks:
  proxy:
    external: true
